# 2D Convolutions With Numpy
The following is an implementation of a 2D convolution of square matrices using only numpy as a backend.

A convolution takes a doubly flipped inputted kernel,

ex. $\mathbb{K}=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \rightarrow
\begin{bmatrix} 4 & 3 \\ 2 & 1\end{bmatrix}$,

and performs element-wise multiplication on all possible windows of a matrix $\mathbb{I}$. Each element of the resulting convolution is equivalent to the sum of element-wise multiplication on a single window.

## Imports


In [0]:
import numpy as np

## Conv2D Function

In [0]:
def conv2d (input_mat, kernel_mat, stride = 1):
  # Tests if arrays are of proper form
  try:
    im = np.array(input_mat)
    x,y = im.shape
  except:
    raise Exception('Input could not be coerced into a 2D numpy array.')
  try:
    km = np.array(kernel_mat)
    u,v = km.shape
  except:
    raise Exception('Kernel could not be coerced into a 2D numpy array.')
  # Tests if arrays are of proper size
  if x != y:
    raise Exception(("Input is expected to be an (n,n) matrix. "
                    "Instead got a matrix of shape ({0},{1}).").format(x, y))
  if u != v:
    raise Exception(("Kernel is expected to be an (n,n) matrix. "
                    "Instead got a matrix of shape ({0},{1}).").format(u, v))
  # Tests if the input is smaller than the kernel
  if x < u:
    raise Exception(("Kernel is too large. Expected kernel of shape "
                    "(n,n), where n <= {0}. Instead got n = {1}.").format(x, u))
  # Checks stride
  if stride < 1 or stride - int(stride) != 0:
    raise Exception('Stride must a positive integer.')

  # Mirrors the kernel for faster convolution
  km_mirror = np.fliplr(np.flipud(km))

  # Creates the output matrix
  output_size = np.ceil((x-u+1)/stride).astype(int)
  output_mat = np.zeros(shape=(output_size, output_size))

  # Performs convolution
  for i in range(output_size):
    si = stride * i
    for j in range(output_size):
      sj = stride * j
      output_mat[i,j] = np.sum(np.multiply(im[si:u+si,sj:u+sj], km_mirror))
  
  return output_mat

## Test Cases

### Sanity Test
$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} \circledast
\begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix} =
\begin{bmatrix} 7 & 10 \\ 16 & 19\end{bmatrix}$

In [0]:
input_mat = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
kernel_mat = [[1,0],
              [0,2]]

print(conv2d(input_mat, kernel_mat))

[[ 7. 10.]
 [16. 19.]]


### Strides
$\mathbb{O}_{(11,11)} = \begin{bmatrix} 1 & \dots & 1 \\ \vdots & \ddots &  \\ 1 &  & 1 \end{bmatrix}$

$\mathbb{O}_{(11,11)} \circledast \mathbb{I}_5 = \begin{bmatrix} 5 & 5 & 5 \\ 5 & 5 & 5 \\ 5 & 5 & 5\end{bmatrix}$ , when stride $=3$

In [0]:
input_mat = np.ones(shape=(11,11))

kernel_mat = np.identity(5)

print(conv2d(input_mat, kernel_mat, 3))

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### Incorrect Input Type

In [0]:
conv2d('This will cause an exception to be raised.',[[1]])

Exception: ignored

### Kernel That is Too Large

In [0]:
input_mat = np.array([[1,2],
                      [3,4]])

kernel_mat = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

print(conv2d(input_mat, kernel_mat))

Exception: ignored

### Empty List

In [0]:
input_mat = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
kernel_mat = [[],
              []]

print(conv2d(input_mat, kernel_mat))

Exception: ignored